# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build with linux toolchain
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Cross-build the project using the container
      - name: linux tool compile using the container on x86 platform
        uses: addnab/docker-run-action@v3
        with:
          image: dockerhy/linux-dbg:latest
          options: --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp
          run: |
            make | tee build_linux.log
                
      - name: linux tool compile using the container on arm platform
        uses: addnab/docker-run-action@v3
        with:
          image: dockerhy/linux-dbg-arm:latest
          options: --platform linux/arm64/v8 --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp
          run: |
            make clean SYSTEM=FT
            make SYSTEM=FT | tee build_linux_FT.log

      - name: dos tool compile using the container
        uses: addnab/docker-run-action@v3
        with:
          image: dockerhy/watcom-docker:latest
          options: --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp
          run: |
            wmake -f makefile_watcom | tee build_dos.log

      - name: Tar files
        run: |
          tar -czvf glendbg.tar.gz ./glendbg.exe ./*.ini
          tar -czvf glenfly_tool_debug.tar.gz ./glenfly_tool_debug ./*.ini
          tar -czvf glenfly_tool_debug_FT.tar.gz ./glenfly_tool_debug_FT ./*.ini
      - name: Archive glendbg
        uses: actions/upload-artifact@v3
        with:
          #name: glendbg
          path: |
            glendbg.tar.gz
            build_*.log
            glenfly_tool_debug_FT.tar.gz
            glenfly_tool_debug.tar.gz        

  send:
    name: Send mail
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download glenfly_tool_debug
        uses: actions/download-artifact@v3
        with:
          name: glenfly_tool_debug
          path: ./
      #- name: get tag
      #  id: tag
      #  uses: dawidd6/action-get-tag@v1
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Build Glenfly debug tool
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECEIVER}}
          # Required sender full name (address can be skipped):
          from: Claire Yu <claireyu@glenfly.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          #cc: "cheerychen@glenfly.com"
          secure: true
          # Optional plain body:
          body: |
            ## Build Done
            
            - Repo: ${{ github.repository }}
            
            ## Version

            #- Version: ${{steps.tag.outputs.tag}}
            - Commit: ${{ github.sha }}
            - Ref: ${{ github.ref_type }} - ${{ github.ref_name }}
            

          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: glenfly_tool_debug.tar.gz,glendbg.tar.gz,glenfly_tool_debug_FT.tar.gz
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
